# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy: nodejsfunctionyaml'
  inputs:
    azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
    appType: functionAppLinux
    appName: nodejsfunctionyaml
    package: '$(System.DefaultWorkingDirectory)/**/'
    runtimeStack: 'DOCKER|microsoft/azure-functions-node8:2.0'
